
void gerador_xml (vend *vendas, quant_vendas) {


fprintf (arquivo,"<nfeProc xmlns=\"http://www.portalfiscal.inf.br/nfe\" versao=\"3.10\">");
fprintf (arquivo,"<NFe xmlns=\"http://www.portalfiscal.inf.br/nfe\">  ");
fprintf (arquivo," <infNFe versao=\"3.10\" Id=NFe35141100776574000741550030007231801234893694>  ");
fprintf (arquivo," <ide>  ");
fprintf (arquivo,"  <cUF>35</cUF> ");
fprintf (arquivo," <cNF>23489369</cNF>  ");
fprintf (arquivo," <natOp>Venda de mercadoria adquir. de terceiros</natOp>  ");
fprintf (arquivo,"  <indPag>0</indPag> ");
fprintf (arquivo," <mod>55</mod>  ");
fprintf (arquivo,"  <serie>3</serie> ");
fprintf (arquivo," <nNF>723180</nNF>  ");
fprintf (arquivo,"<dhEmi>2014-11-17T03:04:42-02:00</dhEmi>  ");
fprintf (arquivo," <dhSaiEnt>2014-11-17T03:04:42-02:00</dhSaiEnt>  ");
fprintf (arquivo," <tpNF>1</tpNF>  ");
fprintf (arquivo,"<idDest>2</idDest>   ");
fprintf (arquivo,"  <cMunFG>3522505</cMunFG>  ");
fprintf (arquivo,"  <tpImp>1</tpImp> ");
fprintf (arquivo,"<tpEmis>1</tpEmis>   ");
fprintf (arquivo," <cDV>4</cDV>  ");
fprintf (arquivo,"  <tpAmb>1</tpAmb>  ");
fprintf (arquivo,"  <finNFe>1</finNFe> ");
fprintf (arquivo,"     <indFinal>1</indFinal> ");
fprintf (arquivo," <indPres>2</indPres>  ");
fprintf (arquivo,"  <procEmi>0</procEmi> ");
fprintf (arquivo," <verProc>ELDOC</verProc>  ");
fprintf (arquivo," </ide>  ");
fprintf (arquivo,"<emit>");
fprintf (arquivo,"<CNPJ>00776574000741</CNPJ>");
fprintf (arquivo,"   <xNome>B2W Companhia Digital</xNome>");
fprintf (arquivo,"\n  <enderEmit> ");  
fprintf (arquivo,"\n <xLgr>Estrada dos Alpes, 555</xLgr>  ");
fprintf (arquivo,"\n  <nro>S/N</nro> ");
fprintf (arquivo,"\n <xBairro>Itaqui</xBairro>  ");
fprintf (arquivo,"\n  <cMun>3522505</cMun> ");
fprintf (arquivo,"\n <xMun>ITAPEVI</xMun>  ");
fprintf (arquivo,"\n  <UF>SP</UF> ");
fprintf (arquivo,"\n  <CEP>06696150</CEP> ");
fprintf (arquivo,"\n  </enderEmit> ");
fprintf (arquivo,"\n   <IE>373117480111</IE> ");
fprintf (arquivo,"\n  <CRT>3</CRT> ");
fprintf (arquivo,"\n </emit>  ");
fprintf (arquivo,"\n  <dest> ");
fprintf (arquivo,"\n    <CPF>05251831404</CPF> ");
fprintf (arquivo,"\n  <xNome>Kalber Roberto Pereira Silva</xNome> ");
fprintf (arquivo,"\n  <enderDest> ");
fprintf (arquivo,"\n   <xLgr>Sao Jose</xLgr> ");
fprintf (arquivo,"\n  <nro>375</nro> ");
fprintf (arquivo,"\n  <xBairro>Cruzeiro</xBairro> ");
fprintf (arquivo,"\n   <cMun>2606408</cMun>");
fprintf (arquivo,"\n <xMun>GRAVATA</xMun>  ");
fprintf (arquivo,"\n  <UF>PE</UF>");
fprintf (arquivo,"\n <CEP>55644360</CEP> ");
fprintf (arquivo,"\n <fone>8198739789</fone>  ");
fprintf (arquivo,"\n   </enderDest>  ");
fprintf (arquivo,"\n  <indIEDest>9</indIEDest> ");
fprintf (arquivo,"\n </dest> ");
fprintf (arquivo,"\n   <det nItem=\"1\"> ");
fprintf (arquivo,"\n  <prod> ");
fprintf (arquivo,"\n <cProd>116607744</cProd>	  ");
fprintf (arquivo,"\n  <cEAN>7892110165099</cEAN> ");
fprintf (arquivo,"\n   <xProd>DVD The Mentalist 5a Temporada (5 discos)</xProd> ");
fprintf (arquivo,"\n <NCM>85234990</NCM>  ");
fprintf (arquivo,"\n  <CFOP>6404</CFOP> ");
fprintf (arquivo,"\n <uCom>PC</uCom>  ");
fprintf (arquivo,"\n <qCom>1</qCom>  ");
fprintf (arquivo,"\n  <vUnCom>54.90</vUnCom> ");
fprintf (arquivo,"\n <vProd>54.90</vProd>  ");
fprintf (arquivo,"\n  <cEANTrib>7892110165099</cEANTrib> ");
fprintf (arquivo,"\n <uTrib>PC</uTrib>  ");
fprintf (arquivo,"\n  <qTrib>1</qTrib> ");
fprintf (arquivo,"\n <vUnTrib>54.90</vUnTrib>  ");
fprintf (arquivo,"\n <vFrete>35.09</vFrete>  ");
fprintf (arquivo,"\n  <indTot>1</indTot> ");
fprintf (arquivo,"\n   </prod> ");
fprintf (arquivo,"\n  <imposto> ");
fprintf (arquivo,"\n <ICMS>  ");
fprintf (arquivo,"\n  <ICMS60> ");
fprintf (arquivo,"\n  <orig>0</orig> ");
fprintf (arquivo,"\n  <CST>60</CST> ");
fprintf (arquivo,"\n  <vBCSTRet>0.00</vBCSTRet> ");
fprintf (arquivo,"\n  <vICMSSTRet>0.00</vICMSSTRet> ");
fprintf (arquivo,"\n  </ICMS60> ");
fprintf (arquivo,"\n </ICMS>  ");
fprintf (arquivo,"\n   <PIS> ");
fprintf (arquivo,"\n  <PISAliq>  ");
fprintf (arquivo,"\n  <CST>01</CST> ");
fprintf (arquivo,"\n <vBC>89.99</vBC>  ");
fprintf (arquivo,"\n  <pPIS>1.65</pPIS> ");
fprintf (arquivo,"\n   <vPIS>1.48</vPIS> ");
fprintf (arquivo,"\n  </PISAliq>  ");
fprintf (arquivo,"\n </PIS>  ");
fprintf (arquivo,"\n  <COFINS> ");
fprintf (arquivo,"\n <COFINSAliq>  ");
fprintf (arquivo,"\n  <CST>01</CST>  ");
fprintf (arquivo,"\n  <vBC>89.99</vBC> ");
fprintf (arquivo,"\n  <pCOFINS>7.60</pCOFINS>  ");
fprintf (arquivo,"\n  <vCOFINS>6.84</vCOFINS> ");
fprintf (arquivo,"\n </COFINSAliq>  ");
fprintf (arquivo,"\n  </COFINS> ");
fprintf (arquivo,"\n  </imposto> ");
fprintf (arquivo,"\n </det>  ");
fprintf (arquivo,"\n  <total> ");
fprintf (arquivo,"\n  <ICMSTot>  ");
fprintf (arquivo,"\n  <vBC>0.00</vBC> ");
fprintf (arquivo,"\n <vICMS>0.00</vICMS>  ");
fprintf (arquivo,"\n  <vICMSDeson>0.00</vICMSDeson>  ");
fprintf (arquivo,"\n   <vBCST>0.00</vBCST> ");
fprintf (arquivo,"\n  <vST>0.00</vST> ");
fprintf (arquivo,"\n  <vProd>54.90</vProd> ");
fprintf (arquivo,"\n <vFrete>35.09</vFrete>  ");
fprintf (arquivo,"\n  <vSeg>0.00</vSeg> ");
fprintf (arquivo,"\n   <vDesc>0.00</vDesc> ");
fprintf (arquivo,"\n  <vII>0.00</vII>  ");
fprintf (arquivo,"\n  <vIPI>0.00</vIPI>  ");
fprintf (arquivo,"\n  <vPIS>1.48</vPIS>  ");
fprintf (arquivo,"\n  <vCOFINS>6.84</vCOFINS> ");
fprintf (arquivo,"\n   <vOutro>0.00</vOutro> ");
fprintf (arquivo,"\n <vNF>89.99</vNF>  ");
fprintf (arquivo,"\n    </ICMSTot> ");
fprintf (arquivo,"\n </total>  ");
fprintf (arquivo,"\n  <transp>  ");
fprintf (arquivo,"\n  <modFrete>1</modFrete> ");
fprintf (arquivo,"\n <vol>  ");
fprintf (arquivo,"\n <qVol>1</qVol>  ");
fprintf (arquivo,"\n  <pesoL>0.150</pesoL>  ");
fprintf (arquivo,"\n <pesoB>0.150</pesoB>  ");
fprintf (arquivo,"\n  </vol> ");
fprintf (arquivo,"\n  </transp>  ");
fprintf (arquivo,"\n  <infAdic> ");
fprintf (arquivo,"\n  <infCpl>Nf.Id: 91217269 -Nao incidencia de ICMS - Mercadoria com Substituicao Tributaria, conforme Art 310 RICMS- 30 de novembro de 2000  Impostos Pagos: ICMS: R$ 3,62 (4,02%) ICMS-ST: R$ 5,01 (5,57%) PIS: R$ 1,48 (1,64%) COFINS: R$ 6,84 (7,60%);  N. Pedido: 02-579585504 N. Entrega: 363230371.</infCpl> ");
fprintf (arquivo,"\n   <obsCont xCampo=\"SiglaERP\">  ");
fprintf (arquivo,"\n  <xTexto>ORACLE</xTexto> ");
fprintf (arquivo,"\n   </obsCont> ");
fprintf (arquivo,"\n <obsCont xCampo=\"Logo\">  ");
fprintf (arquivo,"\n  <xTexto>ACOM</xTexto>	 ");
fprintf (arquivo,"\n  </obsCont> ");
fprintf (arquivo,"\n <obsCont xCampo=\"NomedaMarca\">  ");
fprintf (arquivo,"\n <xTexto>Americanas.com</xTexto>  ");
fprintf (arquivo,"\n     </obsCont> ");
fprintf (arquivo,"\n  </infAdic> ");
fprintf (arquivo,"\n </infNFe>  ");
fprintf (arquivo,"\n  <Signature xmlns=\"http://www.w3.org/2000/09/xmldsig#\"> ");
fprintf (arquivo,"\n <SignedInfo>  ");
fprintf (arquivo,"\n <CanonicalizationMethod Algorithm=\"http://www.w3.org/TR/2001/REC-xml-c14n-20010315\"/>  ");
fprintf (arquivo,"\n   <SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>  ");
fprintf (arquivo,"\n <Reference URI="#NFe35141100776574000741550030007231801234893694">  ");
fprintf (arquivo,"\n <Transforms>  ");
fprintf (arquivo,"\n <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>  ");
fprintf (arquivo,"\n <Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>  ");
fprintf (arquivo,"\n   </Transforms>  ");
fprintf (arquivo,"\n  <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/> ");
fprintf (arquivo,"\n <DigestValue>s64I/lcQq0VrkXNm5T0d+gH32kk=</DigestValue>  ");
fprintf (arquivo,"\n   </Reference> ");
fprintf (arquivo,"\n   </SignedInfo> ");
fprintf (arquivo,"\n  <SignatureValue>aI2CT+F2jbqN4YqQnx6UKwqPm/j8zMmo/cz46nUnzG0dunsujYu+C/IMSZB7wldtzHtdjIzs6FWj3/ApCQ2VnPn/wRUiQvua1Rda+XwHhCg2OWrmEjdlVgcw8P599xLOPV/fcq1Fr6+nGDEJfJGdQbSWOTZrrROKFZgaxlBYXSywSajDgjZti63gTUxaV3DOLNYcD7W/LNSaZ3Gw4B4nSywQyIJhE1XRYsm7TvO4WyeHFQAlzesAmRZnkc4CT3fLJ/x9YqwXqIauZJ7znDoJpuEd/4vWNLGrYSnwMM2QUgnURtI2govjgGlTaRtgWiyNaE7RYhjf92NMimalXwsimA==</SignatureValue> ");
fprintf (arquivo,"\n <KeyInfo>   ");
fprintf (arquivo,"\n <X509Data> ");
fprintf (arquivo,"\n  <X509Certificate>MIIHzjCCBbagAwIBAgIIYX48K/a/QdUwDQYJKoZIhvcNAQELBQAwTDELMAkGA1UEBhMCQlIxEzARBgNVBAoTCklDUC1CcmFzaWwxKDAmBgNVBAMTH1NFUkFTQSBDZXJ0aWZpY2Fkb3JhIERpZ2l0YWwgdjIwHhcNMTQwNTI3MTE1NzAwWhcNMTUwNTI3MTE1NzAwWjCB4DELMAkGA1UEBhMCQlIxEzARBgNVBAoTCklDUC1CcmFzaWwxFDASBgNVBAsTCyhFTSBCUkFOQ08pMRgwFgYDVQQLEw8wMDAwMDEwMDUxNjkwMjUxFDASBgNVBAsTCyhFTSBCUkFOQ08pMRQwEgYDVQQLEwsoRU0gQlJBTkNPKTEUMBIGA1UECxMLKEVNIEJSQU5DTykxFDASBgNVBAsTCyhFTSBCUkFOQ08pMRQwEgYDVQQLEwsoRU0gQlJBTkNPKTEeMBwGA1UEAxMVQjJXIENPTVBBTkhJQSBESUdJVEFMMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnIyLuyXjpHEUdVu3RO6KsWsKjNogkVkB0PHHo+O5RDC+0ManfFDMCocVcrJrPjqkwvtR+CBBqBmNT1fd/SYAHhS2U48uXKeKUybFsiKg49Lrbinb6QuE4n1u+J+/XyexEa3fYhi8Gsnzf89cOeh7SK+I234Pnca0073yqSqs7s6RspT68m6Ixart7+znHfmC87wilhqWemsYlxLM3MdQHg33hhJx4oa/CWs23m5mpVeOtGzrCO0cJyjhppygOOfwuZpr9sA+eVm56GtXdYGCFg93IzFQkB00gnOURPlcXVuVZs6sPdDbkwMKt4I7YdBQfcwxCVz5hONPAaLfga6S/QIDAQABo4IDHTCCAxkwgZcGCCsGAQUFBwEBBIGKMIGHMEcGCCsGAQUFBzAChjtodHRwOi8vd3d3LmNlcnRpZmljYWRvZGlnaXRhbC5jb20uYnIvY2FkZWlhcy9zZXJhc2FjZHYyLnA3YjA8BggrBgEFBQcwAYYwaHR0cDovL29jc3AuY2VydGlmaWNhZG9kaWdpdGFsLmNvbS5ici9zZXJhc2FjZHYyMB8GA1UdIwQYMBaAFJrggxDXJpvputqCsoHOORrTh3CGMHEGA1UdIARqMGgwZgYGYEwBAgEGMFwwWgYIKwYBBQUHAgEWTmh0dHA6Ly9wdWJsaWNhY2FvLmNlcnRpZmljYWRvZGlnaXRhbC5jb20uYnIvcmVwb3NpdG9yaW8vZHBjL2RlY2xhcmFjYW8tc2NkLnBkZjCB8AYDVR0fBIHoMIHlMEmgR6BFhkNodHRwOi8vd3d3LmNlcnRpZmljYWRvZGlnaXRhbC5jb20uYnIvcmVwb3NpdG9yaW8vbGNyL3NlcmFzYWNkdjIuY3JsMEOgQaA/hj1odHRwOi8vbGNyLmNlcnRpZmljYWRvcy5jb20uYnIvcmVwb3NpdG9yaW8vbGNyL3NlcmFzYWNkdjIuY3JsMFOgUaBPhk1odHRwOi8vcmVwb3NpdG9yaW8uaWNwYnJhc2lsLmdvdi5ici9sY3IvU2VyYXNhL3JlcG9zaXRvcmlvL2xjci9zZXJhc2FjZHYyLmNybDAOBgNVHQ8BAf8EBAMCBeAwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMEMIHGBgNVHREEgb4wgbuBHEdBQlJJRUwuU0lMVkFAQjJXRElHSVRBTC5DT02gPgYFYEwBAwSgNRMzMjEwNjE5NjMwNDI4MzMzOTgyMjAwMDAwMDAwMDAwMDAwMDAwMDA3ODUyMDk5U1NQIFNQoCcGBWBMAQMCoB4THEFOTkEgQ0hSSVNUSU5BIFJBTU9TIFNBSUNBTEmgGQYFYEwBAwOgEBMOMDA3NzY1NzQwMDA2NjCgFwYFYEwBAwegDhMMMDAwMDAwMDAwMDAwMA0GCSqGSIb3DQEBCwUAA4ICAQAgE43if0fhqzaLX1AEULKr+syQ2A8XVzid3PjbOrmOL7Nx3Y9M20xqYfDQEwNDZVvavsNbGQUr3prUf6Y5JZaIGoifn+bES2VuPTN04e5WVLNDCcJVSDTyAkbT8yTmLQYwFJJnIHcwFAxFhrwZF6lqbGcEuwvq1HQiRgalugKQJzYyfYlqkoqhWnTY6Ox5BjI2EFfabjIi9fkIWDjw0Xsnrg+M5v4FkafZzZdXoQ/m9Oegs43p4mhNilo733RLEiAM2boMeIP0+T07h6q4UUOI4BG8TH+kY03pUUYKgC9uq9aX7FLGKthMxDukp/6qrsQHPD2hjDgRSU2BYALzk7g1BwW7Nzti3/rGmcGDaML/G/941gCFub3PE6nd1Z+KivGKIkI7K/qkEkvEMEN5ECqGsexV8lTW7CJCSIJT03HL7ZSMco60uS0N9U+E2AWDUovhEdnPfjvfSWi0ksosMxScPx/eKB+20Wn1+4c5Z662/g0II3auQ538ney1wJEEcSpeZzB8Q5dO7tEWPICyTukLZ9NF43rLCPq4mxYdiV0u91xZ3d+wykaIQYIyYyY1QnbPFFLJ83AdIhrDtkhCiDy4oDLaLO/oj5FdcN1vC9zEWmYLYcf/6EqkOeUQL3G0wGyKRXv9lCuPJ7fsFKmYviEVSZI5u6nXpzxHRVbfCfc/KA==</X509Certificate> ");
fprintf (arquivo,"\n</X509Data>   ");
fprintf (arquivo,"\n    </KeyInfo>  ");
fprintf (arquivo,"\n  </Signature> ");
fprintf (arquivo,"\n  </NFe>");
fprintf (arquivo,"\n  <protNFe versao=\"3.10\">");
fprintf (arquivo,"\n <infProt>  ");
fprintf (arquivo,"\n <tpAmb>1</tpAmb>  ");
fprintf (arquivo,"\n  <verAplic>SP_NFE_PL_008d</verAplic>  ");
fprintf (arquivo,"\n   <chNFe>35141100776574000741550030007231801234893694</chNFe> ");
fprintf (arquivo,"\n   <dhRecbto>2014-11-17T03:05:01-02:00</dhRecbto> ");
fprintf (arquivo,"\n  <nProt>135140725516814</nProt> ");
fprintf (arquivo,"\n  <digVal>s64I/lcQq0VrkXNm5T0d+gH32kk=</digVal> ");
fprintf (arquivo,"\n   <cStat>100</cStat>  ");
fprintf (arquivo,"\n   <xMotivo>Autorizado o uso da NF-e</xMotivo> ");
fprintf (arquivo,"\n </infProt>  ");
fprintf (arquivo,"\n   </protNFe> ");
fprintf (arquivo,"\n  </nfeProc> ");


